CREATE TABLE task1.desserts(
id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
uid varchar(300),
dish   varchar(300) ,
description varchar(500) ,
ingredient varchar(500) ,
measurement varchar(300),
load_dttm timestamp DEFAULT current_timestamp
   );