uploader:
  food:
    api_url: 'https://random-data-api.com/api/food/random_food'
    min_batch_size: 1
    max_batch_size: 1
    table: 'task1.food'
  dessert:
    api_url: 'https://random-data-api.com/api/dessert/random_dessert'
    min_batch_size: 1
    max_batch_size: 1
    table: 'task1.desserts'
  request_history:
    table: 'task1.request_history'

db_connect:
    mode: "append"
    url : "jdbc:postgresql://localhost:5432/postgres"
    properties: {"user": "postgres", "password": "postgres", "driver": "org.postgresql.Driver"}

spark:
  app_name: "Python Spark SQL basic example"
  config:
    key: "spark.jars"
    value: "./postgresql-42.5.3.jar"